# Generated by Django 6.1.1 on 2026-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('org_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('team_tag', models.CharField(default='TEAM', max_length=50)),
                ('team_name', models.CharField(default='Esports Team', max_length=255)),
                ('team_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_code_1', models.CharField(default='#1271ff', max_length=20)),
                ('color_code_2', models.CharField(default='#003c67', max_length=20)),
                ('org_shop', models.URLField(blank=True, max_length=500, null=True)),
                ('org_achievements', models.URLField(blank=True, max_length=500, null=True)),
                ('org_youtube_link', models.URLField(blank=True, max_length=500, null=True)),
                ('org_tiktok_link', models.URLField(blank=True, max_length=500, null=True)),
                ('org_instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('org_discord_link', models.URLField(blank=True, max_length=500, null=True)),
                ('org_twitter_link', models.URLField(blank=True, max_length=500, null=True)),
                ('org_country', models.CharField(blank=True, max_length=100, null=True)),
                ('org_address', models.CharField(blank=True, max_length=255, null=True)),
                ('org_working_day', models.CharField(blank=True, max_length=100, null=True)),
                ('org_working_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('org_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('org_whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('org_phone_1', models.CharField(blank=True, max_length=50, null=True)),
                ('org_phone_2', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_tier', models.CharField(default='pro', max_length=50)),
                ('subscription_status', models.CharField(default='active', max_length=50)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_organization',
                'ordering': ['slug'],
            },
        ),
    ]
