# Generated by Django 6.1.1 on 2026-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_url',
            field=models.URLField(blank=True, help_text='Master DB Backend API Url. eg:- https://optech-esports.com/api/master/organizations/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_achievements',
            field=models.URLField(blank=True, help_text='achivement site url .eg:- eg:- https://achivement.optech-esports.com.np/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_domain',
            field=models.CharField(blank=True, help_text='domain name. eg:- https://t2kesports.com.np', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_shop',
            field=models.URLField(blank=True, help_text='shop site url. eg:- https://shop.optech-esports.com.np/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Esport tag url in small eg:- drs, t2k, horra, asl,..etc  ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='team_name',
            field=models.CharField(default='Esports Team', help_text='eg:- Trained To Kill, Horra Esports, Abrupt Slayers, ..etc', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='team_tag',
            field=models.CharField(default='TEAM', help_text='eg:- t2k, drs, horra, ..etc', max_length=50),
        ),
    ]
