# Generated by Django 6.1.1 on 2026-10-03 13:53

import Master.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_organization_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='team_logo_file',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400 (square) PNG with transparent background. Format: PNG, JPG, SVG. Max 5 MB. Overrides the URL above if both are set.', null=True, upload_to=Master.upload_paths.org_logo_upload_to, verbose_name='Team Logo Upload'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='api_url',
            field=models.URLField(blank=True, help_text='Master DB Backend API Url.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_achievements',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_shop',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Esport tag url in small eg:- drs, t2k, horra, asl, ..etc', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='team_logo_url',
            field=models.URLField(blank=True, help_text='Optional: paste a direct image URL. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Team Logo URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='team_name',
            field=models.CharField(default='Esports Team', help_text='eg:- Trained To Kill, Horra Esports, ..etc', max_length=255),
        ),
    ]
