# Generated by Django 6.1.1 on 2026-09-20 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('heading', models.CharField(default='Professional Esports Organizations', max_length=255)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'client_about',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('prize_pool', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_event',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(default='4/3', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_gallery',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_hero',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_sponsor',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('instagram', models.URLField(blank=True, max_length=500)),
                ('tiktok', models.URLField(blank=True, max_length=500)),
                ('youtube', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_team',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('youtube_url', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'client_video',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='Client.about')),
            ],
            options={
                'db_table': 'client_about_paragraph',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Client.about')),
            ],
            options={
                'db_table': 'client_about_stat',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_slug', models.SlugField(max_length=100)),
                ('is_tenant_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_tenant_user',
            },
        ),
    ]
