# Generated by Django 6.1.1 on 2026-09-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='aboutparagraph',
            options={'ordering': ['order', 'id'], 'verbose_name': 'About Paragraph', 'verbose_name_plural': 'About Paragraphs'},
        ),
        migrations.AlterModelOptions(
            name='aboutstat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'About Statistic', 'verbose_name_plural': 'About Statistics'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides'},
        ),
        migrations.AlterModelOptions(
            name='sponsers',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'verbose_name': 'Tenant User Profile', 'verbose_name_plural': 'Tenant User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(default='Professional Esports Organizations', help_text="Main title of the About page section. Example: 'Professional Esports Organization'.", max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True, help_text='Core mission statement summarizing team goals.', verbose_name='Mission Statement'),
        ),
        migrations.AlterField(
            model_name='about',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True, help_text='Long-term vision for the organization.', verbose_name='Vision Statement'),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='about',
            field=models.ForeignKey(help_text='Select the parent About section this paragraph belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='Client.about', verbose_name='About Section'),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls paragraph ordering. Lower numbers appear first (e.g., 0, 1, 2).', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='text',
            field=models.TextField(help_text='Detailed description paragraph introducing the organization.', verbose_name='Paragraph Content'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='about',
            field=models.ForeignKey(help_text='Select the parent About section this statistic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Client.about', verbose_name='About Section'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(help_text="Category or title of this stat. Example: 'Founded', 'Trophies', 'Win Rate'.", max_length=100, verbose_name='Metric Label'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display sequence. Lower numbers appear first (e.g., 0, 1, 2).', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='value',
            field=models.CharField(help_text="Count or score for this stat. Example: '2019', '50+', '87%'.", max_length=50, verbose_name='Metric Value'),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(help_text="Type of match or stage. Example: 'tournament', 'scrim', 'lan'.", max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(help_text="Formatted date range string. Example: 'Dec 15-20, 2026'.", max_length=100, verbose_name='Event Date / Timeframe'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(help_text='Detailed summary or schedule breakdown of the event.', verbose_name='Event Details'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.URLField(help_text='Direct link to promo poster image.', max_length=500, verbose_name='Event Poster/Cover URL'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(help_text="City/Venue or online region. Example: 'Seoul, South Korea', 'Online (ASIA)'.", max_length=200, verbose_name='Location / Venue'),
        ),
        migrations.AlterField(
            model_name='events',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls listing order. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='events',
            name='prize_pool',
            field=models.CharField(help_text="Total cash reward string. Example: '$2,000,000'.", max_length=100, verbose_name='Prize Pool'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(help_text="Current state. Example: 'upcoming', 'ongoing', 'completed'.", max_length=20, verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text="Official tournament or event title. Example: 'World Championship 2026'.", max_length=200, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='aspect_ratio',
            field=models.CharField(default='4/3', help_text="CSS Grid layout proportions. Example: '1/1' (square), '3/4' (portrait), '4/3' or '16/9' (landscape).", max_length=10, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(help_text="Filter grouping tag. Example: 'matches', 'training', 'bootcamp'.", max_length=50, verbose_name='Category Filter'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, help_text="Brief summary or context of the photo. Example: 'Our team celebrating championship victory'.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(help_text='Direct link to full-resolution photo.', max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position sequence in gallery layout. Lower numbers display first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(help_text="Short title describing the image content. Example: 'Team Victory'.", max_length=200, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.URLField(help_text="Direct link to the slide image (e.g., 'https://example.com/banner.jpg').", max_length=500, verbose_name='Banner Image URL'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines slide sequence. Lower numbers appear first (e.g., 0, 1, 2).', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Secondary tag text below title. Example: 'Welcome to the battlefield', 'Train. Kill. Repeat.'", max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tag',
            field=models.CharField(blank=True, help_text="Small category or season badge above title. Example: 'SEASON 2026', 'ESPORT PRO'.", max_length=100, verbose_name='Badge Tag'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(help_text="Primary slide heading. Example: '#RISE AS ONE', 'DOMINATE'.", max_length=200, verbose_name='Main Headline'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='logo',
            field=models.URLField(help_text='Direct link to transparent PNG or SVG logo.', max_length=500, verbose_name='Sponsor Logo URL'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='name',
            field=models.CharField(help_text="Brand name of the partner or sponsor. Example: 'adidas', 'Nike'.", max_length=100, verbose_name='Sponsor Name'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order in sponsor grid. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, help_text="Country flag emoji or code. Example: '🇺🇸', 'NP', 'US'.", max_length=20, verbose_name='Country Flag/Code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.URLField(help_text='Direct link to headshot or jersey picture.', max_length=500, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, help_text='Full link to official Instagram profile.', max_length=500, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text="Official player alias. Example: 'Apex', 'Simple', 'Faker'.", max_length=100, verbose_name='Gamer Tag / In-Game Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls roster line-up placement. Lower numbers display first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='team',
            name='real_name',
            field=models.CharField(blank=True, help_text="Player's actual name. Example: 'John Doe'.", max_length=200, verbose_name='Real Full Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(help_text="Position inside team roster. Example: 'IGL (In-Game Leader)', 'Entry Fragger', 'Head Coach'.", max_length=100, verbose_name='Player Role'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Full link to official TikTok account.', max_length=500, verbose_name='TikTok URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, help_text='Full link to personal channel.', max_length=500, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this tenant user profile was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='is_tenant_admin',
            field=models.BooleanField(default=True, help_text='Designates whether this user has full administrative privileges for this tenant.', verbose_name='Tenant Admin Status'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the tenant organization (e.g., 'cloud9', 'fnatic').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.OneToOneField(help_text='The Django user account linked to this tenant profile.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(help_text="Grouping tag. Example: 'highlights', 'montage', 'interview'.", max_length=50, verbose_name='Video Category'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls video playlist placement. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='organization_slug',
            field=models.SlugField(help_text="Unique identifier for the organization (e.g., 'cloud9').", max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='youtube_url',
            field=models.URLField(help_text="Direct link or embed URL. Example: 'https://youtu.be/sHtBOMbBLZM'.", max_length=500, verbose_name='YouTube Video Link'),
        ),
    ]
