# Generated by Django 6.1.1 on 2026-09-23 08:02

import Client.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_about_options_alter_aboutparagraph_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sponsers',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='events',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a file. Overrides the URL above if both are set.', null=True, upload_to=Client.upload_paths.events_upload_to, verbose_name='Event Poster/Cover Upload'),
        ),
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to promo poster image. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Event Poster/Cover URL'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a file. Overrides the URL above if both are set.', null=True, upload_to=Client.upload_paths.gallery_upload_to, verbose_name='Image Upload'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to full-resolution photo. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a file. Overrides the URL above if both are set.', null=True, upload_to=Client.upload_paths.hero_upload_to, verbose_name='Banner Image Upload'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to the slide image. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Banner Image URL'),
        ),
        migrations.AddField(
            model_name='sponsers',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload a file. Overrides the URL above if both are set.', null=True, upload_to=Client.upload_paths.sponsors_upload_to, verbose_name='Sponsor Logo Upload'),
        ),
        migrations.AddField(
            model_name='sponsers',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Direct link to transparent PNG or SVG logo. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Sponsor Logo URL'),
        ),
        migrations.AddField(
            model_name='team',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a file. Overrides the URL above if both are set.', null=True, upload_to=Client.upload_paths.team_upload_to, verbose_name='Profile Picture Upload'),
        ),
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to headshot or jersey picture. Ignored if a file is uploaded below.', max_length=500, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(default='Professional Esports Organizations', help_text='Main title of the About page section.', max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls paragraph ordering. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(help_text='Category or title of this stat.', max_length=100, verbose_name='Metric Label'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display sequence. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='value',
            field=models.CharField(help_text='Count or score for this stat.', max_length=50, verbose_name='Metric Value'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(help_text='City/Venue or online region.', max_length=200, verbose_name='Location / Venue'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='Official tournament or event title.', max_length=200, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='aspect_ratio',
            field=models.CharField(default='4/3', help_text="CSS Grid layout proportions. Example: '1/1', '3/4', '4/3', '16/9'.", max_length=10, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, help_text='Brief summary or context of the photo.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(help_text='Short title describing the image content.', max_length=200, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines slide sequence. Lower numbers appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Secondary tag text below title. Example: 'Welcome to the battlefield'.", max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tag',
            field=models.CharField(blank=True, help_text="Small category or season badge above title. Example: 'SEASON 2026'.", max_length=100, verbose_name='Badge Tag'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text="Official player alias. Example: 'Apex', 'Faker'.", max_length=100, verbose_name='Gamer Tag / In-Game Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(help_text="Position inside team roster. Example: 'IGL', 'Entry Fragger'.", max_length=100, verbose_name='Player Role'),
        ),
    ]
