# Generated by Django 6.1.1 on 2026-09-26 08:42

import Client.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_remove_events_image_remove_gallery_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutparagraph',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='aboutstat',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sponsers',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(default='Professional Esports Organizations', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='Client.about'),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Client.about'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1600×900 (16:9) or 1600×1200 (4:3). Format: JPG or PNG. Max 5 MB. Auto-compressed to ~150 KB.', null=True, upload_to=Client.upload_paths.events_upload_to, verbose_name='Event Poster Upload'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='prize_pool',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='aspect_ratio',
            field=models.CharField(default='4/3', max_length=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1600×1200 (4:3 landscape) or 1200×1600 (3:4 portrait). Square 1200×1200 also works. Format: JPG or PNG. Max 5 MB. Auto-compressed to ~150 KB.', null=True, upload_to=Client.upload_paths.gallery_upload_to, verbose_name='Image Upload'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080 (16:9) or larger, up to 2560×1440. Format: JPG or PNG. Max 5 MB. Keep the main subject near the center — edges may be cropped on wider screens. Auto-compressed to ~200 KB.', null=True, upload_to=Client.upload_paths.hero_upload_to, verbose_name='Banner Image Upload'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Recommended: 400×400 (square) with transparent background. Format: PNG (transparency preserved) or JPG. Max 5 MB. Auto-compressed to ~30 KB, transparency kept.', null=True, upload_to=Client.upload_paths.sponsors_upload_to, verbose_name='Sponsor Logo Upload'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 800×800 (square). Format: JPG or PNG. Max 5 MB. Face should be centered — card crops to a square. Auto-compressed to ~80 KB.', null=True, upload_to=Client.upload_paths.team_upload_to, verbose_name='Profile Picture Upload'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='real_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='is_tenant_admin',
            field=models.BooleanField(default=True, verbose_name='Tenant Admin Status'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='organization_slug',
            field=models.SlugField(max_length=100, verbose_name='Organization Slug'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videos',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='organization_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='youtube_url',
            field=models.URLField(max_length=500),
        ),
    ]
