# Generated by Django 6.1.1 on 2026-10-03 13:53

import Client.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_aboutparagraph_options_alter_aboutstat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(help_text="Formatted date string. Pick ONE of these formats exactly: (1) Single day — 'Dec 15, 2026'. (2) Same-month range — 'Dec 15-20, 2026'. (3) Full range — 'Dec 15, 2026 - Dec 20, 2026'. Months must be English 3-letter abbreviations (Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec). The system auto-detects event status (upcoming / ongoing / completed) from this date — do not type the status manually.", max_length=100, verbose_name='Event Date / Timeframe'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1600×900 (16:9) or 1600×1200 (4:3). Format: JPG or PNG. Max 5 MB. Auto-compressed to ~150 KB. Only the newest 15 events are kept.', null=True, upload_to=Client.upload_paths.events_upload_to, verbose_name='Event Poster Upload'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(default='upcoming', help_text='Auto-computed from the Date field by the frontend. Whatever you type here is ignored if a valid Date is set.', max_length=20, verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1600×1200 (4:3 landscape) or 1200×1600 (3:4 portrait). Square 1200×1200 also works. Format: JPG or PNG. Max 5 MB. Auto-compressed to ~150 KB. Only the newest 25 photos are kept.', null=True, upload_to=Client.upload_paths.gallery_upload_to, verbose_name='Image Upload'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080 (16:9) or larger, up to 2560×1440. Format: JPG or PNG. Max 5 MB. Keep the main subject near the center — edges may be cropped on wider screens. Auto-compressed to ~200 KB. Only the newest 5 slides are kept.', null=True, upload_to=Client.upload_paths.hero_upload_to, verbose_name='Banner Image Upload'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Recommended: 800×800 (square). Format: JPG or PNG. Max 5 MB. Face should be centered — card crops to a square. Auto-compressed to ~80 KB. Only the newest 20 members are kept.', null=True, upload_to=Client.upload_paths.team_upload_to, verbose_name='Profile Picture Upload'),
        ),
    ]
